#define DIR_PIN 1
#define STEP_PIN 2
#define ENABLE_PIN 3
#define MS1_PIN 4
#define MS2_PIN 5

enum COMMANDS {
    CMD_SET_ORIGIN,
    CMD_SET_MICROSTEPPING,
    CMD_MOVE_UNTIL_CLOSED,
    CMD_ENABLE_STEPPER,
    CMD_DISABLE_STEPPER,
    CMD_DO_STEPS,
    CMD_ROTATE
};

