#define DIR_PIN 13
#define STEP_PIN 12
#define ENABLE_PIN 14
#define MS1_PIN 27
#define MS2_PIN 26

enum COMMANDS {
    CMD_SETUP_STEPPER,
    CMD_SET_ORIGIN,
    CMD_SET_MICROSTEPPING,
    CMD_MOVE_UNTIL_CLOSED,
    CMD_ENABLE_STEPPER,
    CMD_DISABLE_STEPPER,
    CMD_DO_STEPS,
    CMD_ROTATE
};

#define MAX_STEP_DIR 10000

